"""empty message

Revision ID: 2f2e7ebd78cb
Revises: 
Create Date: 2020-03-05 10:40:30.985670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f2e7ebd78cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_ctivity', sa.Column('activity_cost', sa.Float(), nullable=True, comment='活动费用'))
    op.add_column('love_ctivity', sa.Column('adderss', sa.String(length=32), nullable=False, comment='活动地址'))
    op.add_column('love_ctivity', sa.Column('date', sa.DateTime(), nullable=False, comment='活动时间'))
    op.add_column('love_ctivity', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('love_ctivity', sa.Column('money', sa.Float(), nullable=True, comment='活动收费金额'))
    op.add_column('love_ctivity', sa.Column('name', sa.String(length=62), nullable=False, comment='活动名称'))
    op.add_column('love_ctivity', sa.Column('num', sa.Integer(), nullable=True, comment='报名次数'))
    op.add_column('love_ctivity', sa.Column('rule', sa.String(length=500), nullable=True, comment='活动规则'))
    op.add_column('love_ctivity', sa.Column('testarea', sa.String(length=20000), nullable=False, comment='活动简介'))
    op.drop_column('love_ctivity', 'Adderss')
    op.drop_column('love_ctivity', 'Id')
    op.drop_column('love_ctivity', 'Date')
    op.drop_column('love_ctivity', 'Activity_cost')
    op.drop_column('love_ctivity', 'Num')
    op.drop_column('love_ctivity', 'Testarea')
    op.drop_column('love_ctivity', 'Rule')
    op.drop_column('love_ctivity', 'Name')
    op.add_column('love_payment', sa.Column('accounts', sa.String(length=32), nullable=False, comment='转账单号'))
    op.add_column('love_payment', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('love_payment', sa.Column('money', sa.Float(), nullable=False, comment='支付金额'))
    op.add_column('love_payment', sa.Column('status', sa.Boolean(), nullable=False, comment='支付状态'))
    op.add_column('love_payment', sa.Column('uid', sa.Integer(), nullable=True, comment='用户id'))
    op.drop_constraint('love_payment_ibfk_1', 'love_payment', type_='foreignkey')
    op.create_foreign_key(None, 'love_payment', 'love_user', ['uid'], ['id'])
    op.drop_column('love_payment', 'Accounts')
    op.drop_column('love_payment', 'Id')
    op.drop_column('love_payment', 'Money')
    op.drop_column('love_payment', 'Status')
    op.drop_column('love_payment', 'Uid')
    op.add_column('love_record', sa.Column('balance', sa.Float(), nullable=True, comment='余额'))
    op.add_column('love_record', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('love_record', sa.Column('money', sa.Float(), nullable=True, comment='消費金額'))
    op.add_column('love_record', sa.Column('money_sum', sa.Float(), nullable=True, comment='充值金额'))
    op.add_column('love_record', sa.Column('pid', sa.Integer(), nullable=True, comment='支付金额'))
    op.drop_constraint('love_record_ibfk_1', 'love_record', type_='foreignkey')
    op.create_foreign_key(None, 'love_record', 'love_payment', ['pid'], ['id'])
    op.drop_column('love_record', 'Id')
    op.drop_column('love_record', 'Uid')
    op.add_column('love_user', sa.Column('collect', sa.String(length=120), nullable=True, comment='收藏'))
    op.add_column('love_user', sa.Column('ctivity_id', sa.String(length=120), nullable=True, comment='参与活动id'))
    op.add_column('love_user', sa.Column('vip', sa.String(length=2), nullable=True, comment='是否是VIP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_user', 'vip')
    op.drop_column('love_user', 'ctivity_id')
    op.drop_column('love_user', 'collect')
    op.add_column('love_record', sa.Column('Uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用戶id'))
    op.add_column('love_record', sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'love_record', type_='foreignkey')
    op.create_foreign_key('love_record_ibfk_1', 'love_record', 'love_user', ['Uid'], ['id'])
    op.drop_column('love_record', 'pid')
    op.drop_column('love_record', 'money_sum')
    op.drop_column('love_record', 'money')
    op.drop_column('love_record', 'id')
    op.drop_column('love_record', 'balance')
    op.add_column('love_payment', sa.Column('Uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用户id'))
    op.add_column('love_payment', sa.Column('Status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='支付状态'))
    op.add_column('love_payment', sa.Column('Money', mysql.FLOAT(), nullable=False, comment='支付金额'))
    op.add_column('love_payment', sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('love_payment', sa.Column('Accounts', mysql.VARCHAR(length=32), nullable=False, comment='转账单号'))
    op.drop_constraint(None, 'love_payment', type_='foreignkey')
    op.create_foreign_key('love_payment_ibfk_1', 'love_payment', 'love_user', ['Uid'], ['id'])
    op.drop_column('love_payment', 'uid')
    op.drop_column('love_payment', 'status')
    op.drop_column('love_payment', 'money')
    op.drop_column('love_payment', 'id')
    op.drop_column('love_payment', 'accounts')
    op.add_column('love_ctivity', sa.Column('Name', mysql.VARCHAR(length=62), nullable=False, comment='活动名称'))
    op.add_column('love_ctivity', sa.Column('Rule', mysql.VARCHAR(length=500), nullable=True, comment='活动规则'))
    op.add_column('love_ctivity', sa.Column('Testarea', mysql.VARCHAR(length=20000), nullable=False, comment='活动简介'))
    op.add_column('love_ctivity', sa.Column('Num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='报名次数'))
    op.add_column('love_ctivity', sa.Column('Activity_cost', mysql.FLOAT(), nullable=True, comment='活动费用'))
    op.add_column('love_ctivity', sa.Column('Date', mysql.DATETIME(), nullable=False, comment='活动时间'))
    op.add_column('love_ctivity', sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('love_ctivity', sa.Column('Adderss', mysql.VARCHAR(length=32), nullable=False, comment='活动地址'))
    op.drop_column('love_ctivity', 'testarea')
    op.drop_column('love_ctivity', 'rule')
    op.drop_column('love_ctivity', 'num')
    op.drop_column('love_ctivity', 'name')
    op.drop_column('love_ctivity', 'money')
    op.drop_column('love_ctivity', 'id')
    op.drop_column('love_ctivity', 'date')
    op.drop_column('love_ctivity', 'adderss')
    op.drop_column('love_ctivity', 'activity_cost')
    # ### end Alembic commands ###
