"""empty message

Revision ID: 541e79d7a0d6
Revises: 4f3a0e15f055
Create Date: 2020-03-09 17:39:30.722327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541e79d7a0d6'
down_revision = '4f3a0e15f055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_selection', sa.Column('weight', sa.String(length=10), nullable=False, comment='体重范围'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_selection', 'weight')
    # ### end Alembic commands ###
