"""empty message

Revision ID: 614a5bc841ac
Revises: 
Create Date: 2020-03-09 12:13:18.660608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '614a5bc841ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_message', sa.Column('phonecode', sa.String(length=13), nullable=False, comment='电话号码'))
    op.drop_column('love_message', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_message', sa.Column('phone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='电话号码'))
    op.drop_column('love_message', 'phonecode')
    # ### end Alembic commands ###
