"""empty message

Revision ID: 6946711e0d30
Revises: 
Create Date: 2020-03-11 16:24:54.478251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6946711e0d30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_message', 'qq')
    op.drop_column('love_message', 'wechat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_message', sa.Column('wechat', mysql.VARCHAR(length=30), nullable=False, comment='微信号'))
    op.add_column('love_message', sa.Column('qq', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='QQ号'))
    # ### end Alembic commands ###
