"""empty message

Revision ID: 7a9d1cc49a96
Revises: 85ede43ef02f
Create Date: 2020-03-13 15:10:12.566073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9d1cc49a96'
down_revision = '85ede43ef02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_message', sa.Column('age', sa.Integer(), nullable=True, comment='年龄'))
    op.add_column('love_message', sa.Column('sex', sa.String(length=3), nullable=True, comment='性别'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_message', 'sex')
    op.drop_column('love_message', 'age')
    # ### end Alembic commands ###
