"""empty message

Revision ID: 7dbebf6f8f0a
Revises: 814e037393eb
Create Date: 2020-03-08 18:54:20.986496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dbebf6f8f0a'
down_revision = '814e037393eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('love_standatds')
    op.add_column('love_message', sa.Column('rest', sa.String(length=500), nullable=True, comment='其他要求'))
    op.add_column('love_selection', sa.Column('age', sa.Integer(), nullable=False, comment='年龄'))
    op.drop_column('love_selection', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_selection', sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='年龄'))
    op.drop_column('love_selection', 'age')
    op.drop_column('love_message', 'rest')
    op.create_table('love_standatds',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('delete_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='择偶id'),
    sa.Column('marriage', mysql.VARCHAR(length=12), nullable=False, comment='婚史情况'),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='年龄'),
    sa.Column('stature', mysql.VARCHAR(length=4), nullable=False, comment='最低身高要求'),
    sa.Column('weight', mysql.VARCHAR(length=4), nullable=False, comment='体重'),
    sa.Column('monthly', mysql.FLOAT(), nullable=False, comment='月薪'),
    sa.Column('housing', mysql.VARCHAR(length=62), nullable=False, comment='住房情况'),
    sa.Column('vehicle', mysql.VARCHAR(length=3), nullable=False, comment='是否有车'),
    sa.Column('children', mysql.VARCHAR(length=10), nullable=False, comment='有无子女'),
    sa.Column('census', mysql.VARCHAR(length=62), nullable=False, comment='户籍所在地'),
    sa.Column('rests', mysql.VARCHAR(length=500), nullable=True, comment='其他'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
