"""empty message

Revision ID: 814e037393eb
Revises: 
Create Date: 2020-03-06 14:48:16.372929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '814e037393eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_ctivity', 'activity_cost')
    op.add_column('love_user', sa.Column('headimgurl', sa.String(length=120), nullable=True, comment='头像连接'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_user', 'headimgurl')
    op.add_column('love_ctivity', sa.Column('activity_cost', mysql.FLOAT(), nullable=True, comment='活动费用'))
    # ### end Alembic commands ###
