"""empty message

Revision ID: 84e0a301263f
Revises: 614a5bc841ac
Create Date: 2020-03-09 12:15:35.264386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84e0a301263f'
down_revision = '614a5bc841ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_message', sa.Column('phone', sa.String(length=13), nullable=False, comment='电话号码'))
    op.drop_column('love_message', 'phonecode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_message', sa.Column('phonecode', mysql.VARCHAR(length=13), nullable=False, comment='电话号码'))
    op.drop_column('love_message', 'phone')
    # ### end Alembic commands ###
