"""empty message

Revision ID: 85ede43ef02f
Revises: 
Create Date: 2020-03-12 22:40:22.523633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85ede43ef02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_ctivity', sa.Column('initiator', sa.String(length=10), nullable=True, comment='发起人'))
    op.drop_column('love_message', 'nation')
    op.drop_column('love_message', 'blood')
    op.drop_column('love_message', 'presonage')
    op.drop_column('love_message', 'hobby')
    op.drop_column('love_message', 'children')
    op.alter_column('love_selection', 'age',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_comment='年龄')
    op.alter_column('love_selection', 'census',
               existing_type=mysql.VARCHAR(length=62),
               nullable=True,
               existing_comment='户籍所在地')
    op.alter_column('love_selection', 'children',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='有无子女')
    op.alter_column('love_selection', 'housing',
               existing_type=mysql.VARCHAR(length=62),
               nullable=True,
               existing_comment='住房情况')
    op.alter_column('love_selection', 'marriage',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True,
               existing_comment='婚史情况')
    op.alter_column('love_selection', 'monthly',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_comment='月薪范围')
    op.alter_column('love_selection', 'stature',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True,
               existing_comment='最低身高要求')
    op.alter_column('love_selection', 'vehicle',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True,
               existing_comment='是否有车')
    op.alter_column('love_selection', 'weight',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='体重范围')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('love_selection', 'weight',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='体重范围')
    op.alter_column('love_selection', 'vehicle',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False,
               existing_comment='是否有车')
    op.alter_column('love_selection', 'stature',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False,
               existing_comment='最低身高要求')
    op.alter_column('love_selection', 'monthly',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_comment='月薪范围')
    op.alter_column('love_selection', 'marriage',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False,
               existing_comment='婚史情况')
    op.alter_column('love_selection', 'housing',
               existing_type=mysql.VARCHAR(length=62),
               nullable=False,
               existing_comment='住房情况')
    op.alter_column('love_selection', 'children',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='有无子女')
    op.alter_column('love_selection', 'census',
               existing_type=mysql.VARCHAR(length=62),
               nullable=False,
               existing_comment='户籍所在地')
    op.alter_column('love_selection', 'age',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_comment='年龄')
    op.add_column('love_message', sa.Column('children', mysql.VARCHAR(length=10), nullable=True, comment='有无子女'))
    op.add_column('love_message', sa.Column('hobby', mysql.VARCHAR(length=120), nullable=True, comment='兴趣爱好'))
    op.add_column('love_message', sa.Column('presonage', mysql.VARCHAR(length=500), nullable=True, comment='个人介绍'))
    op.add_column('love_message', sa.Column('blood', mysql.VARCHAR(length=6), nullable=True, comment='血型'))
    op.add_column('love_message', sa.Column('nation', mysql.VARCHAR(length=12), nullable=True, comment='民族'))
    op.drop_column('love_ctivity', 'initiator')
    # ### end Alembic commands ###
