"""empty message

Revision ID: 89311980ce03
Revises: 
Create Date: 2020-03-09 17:22:52.339342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89311980ce03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('love_message', 'monthly2')
    op.add_column('love_selection', sa.Column('age_bracket', sa.String(length=30), nullable=False, comment='年龄'))
    op.add_column('love_selection', sa.Column('monthly', sa.String(length=30), nullable=False, comment='月薪范围'))
    op.drop_column('love_selection', 'monthly2')
    op.drop_column('love_selection', 'monthly1')
    op.drop_column('love_selection', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_selection', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='年龄'))
    op.add_column('love_selection', sa.Column('monthly1', mysql.FLOAT(), nullable=False, comment='月薪'))
    op.add_column('love_selection', sa.Column('monthly2', mysql.FLOAT(), nullable=False, comment='月薪'))
    op.drop_column('love_selection', 'monthly')
    op.drop_column('love_selection', 'age_bracket')
    op.add_column('love_message', sa.Column('monthly2', mysql.FLOAT(), nullable=True, comment='月薪'))
    # ### end Alembic commands ###
