"""empty message

Revision ID: bf7e2e2b3c95
Revises: 9424a97a7dfb
Create Date: 2020-03-16 11:34:40.845061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf7e2e2b3c95'
down_revision = '9424a97a7dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_ctivity', sa.Column('address', sa.String(length=32), nullable=False, comment='活动地址'))
    op.add_column('love_ctivity', sa.Column('images', sa.String(length=60), nullable=True, comment='活动封面图片'))
    op.drop_column('love_ctivity', 'adderss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('love_ctivity', sa.Column('adderss', mysql.VARCHAR(length=32), nullable=False, comment='活动地址'))
    op.drop_column('love_ctivity', 'images')
    op.drop_column('love_ctivity', 'address')
    # ### end Alembic commands ###
