"""empty message

Revision ID: cbfadac26326
Revises: 7dbebf6f8f0a
Create Date: 2020-03-08 21:51:18.548630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfadac26326'
down_revision = '7dbebf6f8f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'love_message', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'love_message', type_='unique')
    # ### end Alembic commands ###
